services:
  backend:
    build:
      context: ./src/backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "8002:8002"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
 