# Dockerfile.backend

# Usa la imagen de Python como base
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /src

# Copia el archivo de requisitos
COPY ../../requirements.txt ./

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de la aplicación
COPY . .

# Exponer el puerto donde corre FastAPI
EXPOSE 8000

# Comando para iniciar la aplicación
CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
